import {test} from 'node:test';
import assert from 'node:assert/strict';
import {orderText,telegramLink,reconcileCart,toRow,fromRow,publicConfigValid} from '../src/core.js';
const p={id:1,name:'Dell & Lenovo? #1',brand:'Dell',cat:0,status:0,price:10.15,images:[],ram:'16',descUk:'Опис',descPl:'Opis'};
test('Telegram draft preserves Unicode and special characters and uses fixed recipient',()=>{const text=orderText([p,{...p,id:2,price:20.2}],'uk','https://shop.example');const url=new URL(telegramLink(text));assert.equal(url.hostname,'t.me');assert.equal(url.pathname,'/HUGO_Media');assert.equal(url.searchParams.get('text'),text);assert.match(text,/30.35 zł/);assert.match(text,/\?product=2/);});
test('cart removes unavailable, missing and duplicate products',()=>{assert.deepEqual(reconcileCart([1,1,2,3,4],[p,{...p,id:2,status:1},{...p,id:3,status:2}]),[1]);});
test('database mapping roundtrips bilingual text and specs without granting injected fields',()=>{const row=toRow({...p,role:'admin',created_at:'fake'});assert.equal(row.role,undefined);assert.equal(row.created_at,undefined);assert.equal(fromRow(row).descUk,'Опис');assert.equal(fromRow(row).ram,'16');});
test('invalid product cannot reach data API mapping',()=>{for(const patch of [{price:-1},{price:NaN},{cat:6},{status:4},{name:' '},{brand:''},{images:Array(9).fill('x')}])assert.throws(()=>toRow({...p,...patch}));});
test('public config refuses service-role and secret keys and invalid origins',()=>{const jwt=role=>'x.'+Buffer.from(JSON.stringify({role})).toString('base64url')+'.x';const url='https://example.supabase.co';assert.equal(publicConfigValid({supabaseUrl:url,supabaseKey:jwt('service_role')}),false);assert.equal(publicConfigValid({supabaseUrl:url,supabaseKey:'sb_secret_secret'}),false);assert.equal(publicConfigValid({supabaseUrl:url,supabaseKey:jwt('anon')}),true);assert.equal(publicConfigValid({supabaseUrl:'https://example.supabase.co.attacker.test',supabaseKey:jwt('anon')}),false);});
