import {UPGRADES,upgradeOptions,configuration,bundleLabel,BUNDLES,csv,effectivePrice,capacityGB} from './core.js';
export function adminUpgrades(p,lang,esc){
 const L=(u,pl)=>lang==='pl'?pl:u;
 return `<section class="hp-form-section"><h3>${L('Апгрейди RAM / SSD','Rozbudowa RAM / SSD')}</h3><p class="hp-muted">${L('Тільки для ноутбуків. Увімкни опцію лише після перевірки слотів, сумісності та максимального обсягу. Нові компоненти; доплата включає монтаж і перевірку. Ціни можна змінити.','Tylko dla laptopów. Włącz opcję po sprawdzeniu gniazd, zgodności i maksymalnej pojemności. Nowe części; dopłata obejmuje montaż i test. Ceny można zmienić.')}</p><div class="hp-form-grid">${Object.entries(UPGRADES).map(([key,o])=>{const suggested=key==='ram16'?399:key==='ram32'?999:key==='ssd512'?499:capacityGB(p.ssd)>=512?649:749;return `<fieldset class="hm-upgrade-admin"><legend>${o.group==='ram'?'RAM': 'SSD'} → ${o.target===1024?'1 TB':o.target+' GB'}</legend><label class="hp-field">${L('Доступність','Dostępność')}<select name="${key}Enabled"><option value="">${L('Недоступно / не перевірено','Niedostępne / niesprawdzone')}</option><option value="true" ${p[key+'Enabled']==='true'?'selected':''}>${L('Доступно — сумісність перевірена','Dostępne — zgodność sprawdzona')}</option></select></label><label class="hp-field">${L('Доплата з монтажем, zł','Dopłata z montażem, zł')}<input type="number" name="${key}Price" min="0" max="10000" step="0.01" value="${esc(p[key+'Price']??String(suggested))}"></label></fieldset>`}).join('')}</div><p class="hp-muted">${L('32 GB: орієнтир +599 zł, якщо достатньо однієї планки 16 GB; +999 zł, якщо потрібні дві нові. Вкажи відповідну доплату. Клієнт обирає кінцевий обсяг, а не кількість доданих гігабайтів.','32 GB: orientacyjnie +599 zł za jedną kość 16 GB lub +999 zł za dwie nowe. Ustaw właściwą dopłatę. Klient wybiera docelową pojemność.')}</p></section>`;
}
export function configPanel(p,bundles,upgrades,lang,esc,money){
 const L=(u,pl)=>lang==='pl'?pl:u, result=configuration(p,bundles,upgrades,lang),opts=upgradeOptions(p);
 const available=csv(p.bundles).filter(k=>Object.hasOwn(BUNDLES,k)&&!(k==='upgrade'&&opts.length));
 if(!opts.length&&!available.length)return '';
 return `<section class="hm-configurator" data-config-panel="${p.id}"><h3>${L('Збери свій комплект','Skonfiguruj zestaw')}</h3><div class="hm-config-options">${['ram','ssd'].map(group=>{const list=opts.filter(o=>o.group===group);if(!list.length)return '';return `<label class="hp-field">${group==='ram'?L('Оперативна пам’ять','Pamięć RAM'):L('Накопичувач SSD','Dysk SSD')}<select data-upgrade="${group}" data-product="${p.id}"><option value="">${esc(p[group]||'—')} — ${L('у вартості ноутбука','w cenie laptopa')}</option>${list.map(o=>`<option value="${o.key}" ${result.upgrades[group]===o.key?'selected':''}>${o.target===1024?'1 TB':o.target+' GB'} (+${money(o.price)} zł)</option>`).join('')}</select></label>`;}).join('')}</div>${opts.length?`<p class="hp-muted hp-small">${L('Нові компоненти з монтажем. SSD — заміна.','Nowe części z montażem. SSD — wymiana.')}</p>`:''}${available.length?`<div id="hm-config-extras" class="hm-config-extras"><div class="hm-extras-heading">${L('Аксесуари та послуги','Akcesoria i usługi')}<span>${result.bundles.length?L('Вибрано: ','Wybrano: ')+result.bundles.length:'+'+available.length}</span></div><div class="hp-bundle-list">${available.map(k=>`<label><input type="checkbox" data-bundle="${k}" data-product="${p.id}" ${result.bundles.includes(k)?'checked':''}><span>${esc(bundleLabel(k,lang))}${BUNDLES[k]?` +${money(BUNDLES[k])} zł`:''}</span></label>`).join('')}</div></div>`:''}<div class="hm-config-breakdown"><div><span>${L('Ноутбук / товар','Laptop / produkt')}</span><b>${money(effectivePrice(p))} zł</b></div>${result.lines.map(l=>`<div><span>${esc(l.label)}</span><b>${l.pending?L('Уточнити','Do ustalenia'):'+'+money(l.price)+' zł'}</b></div>`).join('')}<div class="hm-config-total" aria-live="polite"><span>${L('Разом','Razem')}</span><strong>${money(result.total)} zł</strong></div>${result.pending?`<p>${L('Послуги за запитом не включені в суму. Їхню ціну погодимо окремо.','Usługi na zapytanie nie są wliczone. Ich cenę uzgodnimy osobno.')}</p>`:''}</div></section>`;
}
