import { createInsights } from './insights.js';
import { effectivePrice, csv, TELEGRAM_CHANNEL, fromRow } from './core.js';
import { LINK_SLOTS, TRUST_SECTIONS, validateSettings, normalizeInvite, productIssues, rankLaptops, selectionIds, shareSelection, availableProduct, publicProduct, draftValues } from './enhancement-core.js';
import * as drafts from './drafts.js';

export function createEnhancements(c) {
 const L=(uk,pl)=>c.lang==='pl'?pl:uk, E=c.esc;
 const insights=createInsights(c);
 const issueLabels=()=>({price:L('Некоректна ціна','Nieprawidłowa cena'),stock:L('У наявності, але кількість нуль','Dostępny, ale ilość zero'),mismatch:L('Назва й характеристики відрізняються — перевір','Nazwa i parametry różnią się — sprawdź'),broken:L('Фото не завантажилось — перевір','Zdjęcie nie załadowało się — sprawdź'),photos:L('Немає фото','Brak zdjęć'),post:L('Немає посилання на пост','Brak linku do posta'),warranty:L('Не вказана гарантія','Brak gwarancji'),condition:L('Не вказано стан','Brak stanu'),charger:L('Не вказана комплектація зарядки','Brak informacji o ładowarce'),uk:L('Немає українського опису','Brak opisu ukraińskiego'),pl:L('Немає польського опису','Brak opisu polskiego'),photoKind:L('Не вказано джерело фото','Brak źródła zdjęć'),stale:L('Не оновлювався понад 30 днів','Nieaktualizowany ponad 30 dni')});
 const slotLabels=()=>({start:L('Стартовий екран','Ekran startowy'),catalog:L('Головна й каталог','Strona główna i katalog'),product:L('Картка товару: підписка','Produkt: subskrypcja'),footer:L('Низ сайту','Stopka'),floating:L('Плаваюча кнопка','Przycisk pływający')});
 const trustLabels=()=>({warranty:L('Гарантія','Gwarancja'),payment:L('Оплата','Płatność'),delivery:L('Доставка','Dostawa'),inspection:L('Перевірка','Sprawdzenie'),returns:L('Повернення й обмін','Zwroty i wymiany')});
 const photoLabels=()=>({'':L('Джерело фото не вказано','Źródło zdjęć niepodane'),actual:L('Фото цього екземпляра','Zdjęcia tego egzemplarza'),model:L('Ілюстративне фото моделі','Zdjęcie poglądowe modelu'),mixed:L('Фото моделі та цього екземпляра','Zdjęcia modelu i tego egzemplarza')});
 let settings={links:{},trust:{}}, settingsError=false;
 let quiz={budget:'1500',purpose:'study',size:'any'}, quizStep=0, quizResults=false;
 let recent=c.readLocal('hmg-recent-products',[]);if(!Array.isArray(recent))recent=[];
 let shared=selectionIds(new URLSearchParams(location.search).get('selection')||'');
 let versions=[], versionProduct=null, versionError=false, versionLoading=false;
 let draftTimer, draftChain=Promise.resolve(), editorForm=null, editorBase=null, draftPending=null, dirty=false, draftError=false, restoring=false, editGeneration=0;
 const q=(s)=>c.root.querySelector(s), content=()=>q('#hp-content');
 const button=(action,label,primary=false,extra='')=>`<button type="button" class="hp-button ${primary?'hp-primary':''}" data-grow="${action}" ${extra}>${label}</button>`;
 function message(err){return /editConflict/.test(err?.message||'')?L('Товар або налаштування вже змінив інший адміністратор. Онови сторінку; чернетка залишиться на цьому пристрої.','Produkt lub ustawienia zmienił inny administrator. Odśwież stronę; szkic pozostanie na tym urządzeniu.'):err?.message==='invalidInvite'?L('Встав посилання https://t.me/+… зі свого каналу або https://t.me/h_m_g_pl.','Wklej link https://t.me/+… ze swojego kanału lub https://t.me/h_m_g_pl.'):L('Не вдалося зберегти. Перевір з’єднання та повтори.','Nie udało się zapisać. Sprawdź połączenie i spróbuj ponownie.');}
 async function reloadSettings(){try{settings=await c.db.readSettings();settingsError=false;}catch{settingsError=true;}}
 function channelUrl(slot){return normalizeInvite(settings.links?.[slot])||TELEGRAM_CHANNEL;}
 function sectionHeader(title,desc=''){return `<div class="hp-intro"><div><h1>${title}</h1>${desc?`<p class="hp-muted">${desc}</p>`:''}</div></div>`;}
 function adminTabs(){return `<div class="hp-admin-tabs hp-extra-tabs">${['quality','drafts','settings'].map((v,i)=>button(v,[L('Потребує уваги','Wymaga uwagi'),L('Чернетки','Szkice'),L('Telegram і довіра','Telegram i zaufanie')][i],c.view===v)).join('')}</div>`;}
 function navigate(view){c.setView(view);history.replaceState(null,'',view==='finder'?'/?finder':view==='shared'?`/?selection=${shared.join(',')}`:`/?admin=${view}`);c.render();window.scrollTo(0,0);}
 function finderCTA(){return `<section class="hp-finder-cta"><div><strong>${L('Який ноутбук підійде саме тобі?','Jaki laptop będzie dla Ciebie?')}</strong><p>${L('Бюджет, задачі, розмір — підберемо до трьох моделей.','Budżet, zastosowanie, rozmiar — wybierzemy do trzech modeli.')}</p></div>${button('finder',L('Підібрати за 30 секунд','Dobierz w 30 sekund'),true)}</section>`;}
 function renderFinder(){
 const purposeOptions=['study','office','programming','editing','gaming','travel'];
 const titles=[L('Який твій бюджет?','Jaki masz budżet?'),L('Для чого потрібен ноутбук?','Do czego potrzebujesz laptopa?'),L('Який розмір зручний?','Jaki rozmiar będzie wygodny?')];
 let body='';
 if(quizResults){const results=rankLaptops(c.products,quiz);body=`<h2>${L('Твій підбір','Twój wybór')}</h2><p>${L('До','Do')} ${E(quiz.budget)} zł · ${c.t('purpose'+quiz.purpose[0].toUpperCase()+quiz.purpose.slice(1))}</p>${results.length?`<p class="hp-muted">${L('За вказаними характеристиками та призначенням. Сумісність із конкретною грою чи програмою уточни перед покупкою.','Na podstawie parametrów i zastosowania. Przed zakupem sprawdź zgodność z konkretną grą lub programem.')}</p><div class="hp-finder-results">${results.map(({product:p,reasons})=>`<div><p class="hp-match-reason">${L('У межах бюджету','W budżecie')} · ${E(p.ram)} GB RAM${p.screen?` · ${E(p.screen)}″`:''}${reasons.includes('purpose')?` · ${c.t('purpose'+quiz.purpose[0].toUpperCase()+quiz.purpose.slice(1))}`:''}</p>${c.productCard(p)}</div>`).join('')}</div>`:`<div class="hp-empty"><h3>${L('Точного збігу поки немає','Na razie brak dokładnego dopasowania')}</h3><p>${L('Зміни бюджет або параметри. Можеш написати нам — допоможемо з підбором.','Zmień budżet lub parametry albo napisz do nas — pomożemy.')}</p><a class="hp-button hp-primary" href="https://t.me/HUGO_Media" data-track-target="telegram_contact" target="_blank" rel="noopener noreferrer">${c.t('writeTelegram')}</a></div>`}${button('quiz-reset',L('Змінити відповіді','Zmień odpowiedzi'))}`;
 }else{body=`<div class="hp-quiz-progress" aria-label="${L('Крок','Krok')} ${quizStep+1}/3">${titles.map((_,i)=>`<span class="${i<=quizStep?'is-active':''}"></span>`).join('')}</div><p class="hp-kicker">${L('Крок','Krok')} ${quizStep+1} / 3</p><h2>${titles[quizStep]}</h2><form id="hp-quiz-form">${quizStep===0?`<label class="hp-field">${L('Максимальна ціна, zł','Maksymalna cena, zł')}<input type="number" name="budget" min="1" max="10000000" step="1" value="${E(quiz.budget)}" required></label><div class="hp-quiz-options">${[1000,1500,2000,3000].map(v=>button('budget',`${v} zł`,false,`data-value="${v}"`)).join('')}</div>`:quizStep===1?`<fieldset class="hp-choice-grid"><legend class="hp-sr-only">${titles[1]}</legend>${purposeOptions.map(v=>`<label><input type="radio" name="purpose" value="${v}" ${quiz.purpose===v?'checked':''}><span>${c.t('purpose'+v[0].toUpperCase()+v.slice(1))}</span></label>`).join('')}</fieldset>`:`<fieldset class="hp-choice-grid"><legend class="hp-sr-only">${titles[2]}</legend>${[['any',L('Будь-який','Dowolny')],['compact',L('Компактний — до 14″','Kompaktowy — do 14″')],['large',L('Більший екран — понад 14″','Większy ekran — ponad 14″')]].map(([v,l])=>`<label><input type="radio" name="size" value="${v}" ${quiz.size===v?'checked':''}><span>${l}</span></label>`).join('')}</fieldset>`}<div class="hp-form-actions">${quizStep?button('quiz-back',L('Назад','Wstecz')):''}<button class="hp-button hp-primary" type="submit">${quizStep===2?L('Показати моделі','Pokaż modele'):L('Далі','Dalej')}</button></div></form>`;}
 content().innerHTML=`${button('catalog',c.t('back'))}<section class="hp-quiz ${quizResults?'hp-quiz-wide':''}">${body}</section>`;
 }
 function remember(id){if(c.admin)return;recent=[id,...recent.filter(v=>v!==id)].slice(0,8);c.writeLocal('hmg-recent-products',recent);}
 function recentBlock(){const items=recent.filter(id=>id!==c.selected||c.view!=='detail').map(id=>c.products.find(p=>p.id===id&&availableProduct(p))).filter(Boolean).slice(0,4);if(!items.length)return '';
 return `<section class="hp-home-section hp-recent"><div class="hp-section-title"><h2>${L('Нещодавно переглянуті','Ostatnio oglądane')}</h2>${button('clear-recent',L('Очистити','Wyczyść'))}</div><div class="hp-grid">${items.map(c.productCard).join('')}</div></section>`;}
 function renderShared(){const items=shared.map(id=>c.products.find(p=>p.id===id&&publicProduct(p))).filter(Boolean), missing=shared.length-items.length;
 content().innerHTML=`${sectionHeader(L('З тобою поділилися вибором','Udostępniona lista'),L('Ціни та наявність актуальні на момент відкриття.','Ceny i dostępność są aktualne w chwili otwarcia.'))}${missing?`<p class="hp-note">${L('Деякі товари з цього списку вже недоступні.','Niektóre produkty z tej listy są już niedostępne.')}</p>`:''}${items.length?`<div class="hp-grid">${items.map(p=>`<section>${availableProduct(p)?c.productCard(p):`<article class="hp-shared-unavailable"><h3>${E(p.name)}</h3><p>${c.t('statuses')[p.status]}</p><button type="button" class="hp-button" data-detail="${p.id}">${c.t('cardDetails')}</button></article>`}</section>`).join('')}</div>${button('shared-add',L('Додати доступні товари до мого вибору','Dodaj dostępne produkty do mojej listy'),true)}`:`<p class="hp-empty">${L('У списку немає доступних товарів.','Brak dostępnych produktów na liście.')}</p>`}${button('catalog',c.t('continue'))}`;
 }
 let photoFailures=new Set(),photoChecking=false,photoChecked=false;
 async function checkPhotos(){
  if(photoChecking)return;photoChecking=true;photoChecked=false;photoFailures.clear();renderQuality();
  const tasks=c.products.filter(p=>[0,3].includes(p.status)).flatMap(p=>(p.images||[]).map(path=>({id:p.id,path})));
  let cursor=0;await Promise.all(Array.from({length:4},async()=>{while(cursor<tasks.length){const task=tasks[cursor++];const ok=await new Promise(resolve=>{const img=new Image();const timer=setTimeout(()=>{img.src="";resolve(false);},10000);img.onload=()=>{clearTimeout(timer);resolve(img.naturalWidth>0);};img.onerror=()=>{clearTimeout(timer);resolve(false);};img.src=c.db.photoUrl(task.path);});if(!ok)photoFailures.add(task.id);}}));
  photoChecking=false;photoChecked=true;if(c.view==="quality"&&c.admin)renderQuality();
 }
 function renderQuality(){const labels=issueLabels(), items=c.products.filter(p=>p.status===0||p.status===3).map(p=>({p,issues:[...productIssues(p),...(photoFailures.has(p.id)?["broken"]:[])]})).filter(x=>x.issues.length);
 content().innerHTML=`${c.adminNav('quality')}${sectionHeader(L('Потребує уваги','Wymaga uwagi'),L('Активні товари та чернетки. Підказки допомагають заповнити картки; вони не блокують публікацію.','Aktywne produkty i szkice. Wskazówki pomagają uzupełnić dane; nie blokują publikacji.'))}${button("check-photos",photoChecking?L("Перевіряю фото…","Sprawdzam zdjęcia…"):L("Перевірити завантаження фото","Sprawdź ładowanie zdjęć"),false,photoChecking?"disabled":"")}<p>${photoChecked?L("Перевірку завершено. Помилка завантаження може бути тимчасовою — перевір фото перед заміною.","Sprawdzono. Błąd może być tymczasowy — sprawdź zdjęcie przed wymianą."):L("Фото перевіряються за кнопкою. Позначки характеристик — підказки для ручної перевірки.","Zdjęcia sprawdzamy po kliknięciu. Oznaczenia parametrów wymagają ręcznej weryfikacji.")}</p><div class="hp-quality-summary"><strong>${items.length}</strong><span>${L('карток варто доповнити','kart do uzupełnienia')}</span></div><div class="hp-quality-list">${items.map(({p,issues})=>`<article><div><strong>${E(p.name)}</strong><small>HMG-${p.id} · ${c.t('statuses')[p.status]}</small><div class="hp-issue-tags">${issues.map(k=>`<span>${labels[k]}</span>`).join('')}</div></div><button type="button" class="hp-button" data-edit="${p.id}">${c.t('edit')}</button></article>`).join('')||`<p>${L('Усі картки заповнені.','Wszystkie karty są uzupełnione.')}</p>`}</div>`;
 }
 function renderSettings(){const slots=slotLabels(), trusts=trustLabels();
 content().innerHTML=`${c.adminNav('settings')}${sectionHeader(L('Telegram і довіра','Telegram i zaufanie'))}${settingsError?`<p role="alert">${L('Не вдалося завантажити налаштування. Онови їх перед редагуванням.','Nie udało się załadować ustawień. Odśwież je przed edycją.')}</p>${button('reload-settings',L('Повторити','Ponów'))}`:`<form id="hp-settings-form" class="hp-form"><section class="hp-form-section"><h2>${L('Запрошення в Telegram','Zaproszenia do Telegrama')}</h2><p>${L('У Telegram: профіль каналу → Редагувати → Запрошувальні посилання. Створи окреме посилання для кожного місця й встав сюди. Порожнє поле використовує основну адресу каналу.','W Telegramie: profil kanału → Edytuj → Linki zaproszeń. Utwórz osobny link dla każdego miejsca i wklej tutaj. Puste pole używa głównego adresu kanału.')}</p><p class="hp-muted">${L('Натискання видно в аналітиці сайту. Фактичні приєднання — у статистиці запрошувальних посилань Telegram.','Kliknięcia widać w analityce strony. Faktyczne dołączenia — w statystykach linków zaproszeń Telegrama.')}</p><div class="hp-form-grid">${LINK_SLOTS.map(k=>`<label class="hp-field">${slots[k]}<input name="link_${k}" type="url" maxlength="300" placeholder="https://t.me/+…" value="${E(settings.links?.[k]||'')}"></label>`).join('')}</div></section><section class="hp-form-section"><h2>${L('Умови для покупців','Warunki dla kupujących')}</h2><p>${L('Заповни фактичні умови українською й польською. Вони з’являться на головній і в картках товарів. Якщо поле порожнє, залишається поточний текст.','Wpisz rzeczywiste warunki po ukraińsku i polsku. Pojawią się na stronie głównej i przy produktach. Puste pole zachowuje dotychczasowy tekst.')}</p>${TRUST_SECTIONS.map(k=>`<fieldset class="hp-trust-editor"><legend>${trusts[k]}</legend><div class="hp-form-grid">${['uk','pl'].map(l=>`<label class="hp-field">${l==='uk'?'Українська':'Polski'}<textarea name="trust_${k}_${l}" maxlength="2000" rows="4">${E(settings.trust?.[k]?.[l]||'')}</textarea></label>`).join('')}</div></fieldset>`).join('')}</section><p id="hp-settings-message" role="status"></p><button type="submit" class="hp-button hp-primary">${c.t('save')}</button></form>`}`;
 }
 function trustBlock(){const titles=trustLabels();return `<section class="hp-product-terms"><h2>${c.t('trustDetails')}</h2>${TRUST_SECTIONS.map(k=>`<details><summary>${titles[k]}</summary><p>${E(settings.trust?.[k]?.[c.lang]||c.t('trust'+k[0].toUpperCase()+k.slice(1)+'Text'))}</p></details>`).join('')}</section>`;}
 function renderPlacements(){const events=c.analyticsEvents.filter(e=>e.event_type==='telegram_click'&&e.destination==='telegram_channel'),labels=slotLabels();return `<section class="hp-stat-panel hp-placements"><h3>${L('Звідки переходять у канал','Skąd przechodzą do kanału')}</h3><p>${L('Натискання за вибраний період, серед відвідувачів зі згодою на аналітику. Це переходи, а не підтверджені підписки. Старі події без позначки місця винесено окремо.','Kliknięcia w wybranym okresie wśród odwiedzających ze zgodą na analitykę. To przejścia, nie potwierdzone subskrypcje. Starsze zdarzenia bez oznaczenia miejsca są osobno.')}</p><div class="hp-table-scroll"><table><thead><tr><th>${L('Місце','Miejsce')}</th><th>${L('Кліки','Kliknięcia')}</th><th>${L('Відвідувачі','Odwiedzający')}</th><th>${L('Джерела','Źródła')}</th></tr></thead><tbody>${[...LINK_SLOTS,''].map(slot=>{const rows=events.filter(e=>(e.placement||'')===slot),sources={};rows.forEach(e=>{const key=e.traffic_source||'direct';sources[key]=(sources[key]||0)+1;});return `<tr><th>${labels[slot]||L('Раніше, без позначки','Starsze, bez oznaczenia')}</th><td>${rows.length}</td><td>${new Set(rows.map(e=>e.visitor_id)).size}</td><td>${Object.entries(sources).map(([k,v])=>`${E(k)}: ${v}`).join(' · ')||'—'}</td></tr>`;}).join('')}</tbody></table></div>${button('settings',L('Налаштувати посилання','Ustaw linki'))}</section>`;}
 async function renderDraftList(){const user=c.db.currentUserId;content().innerHTML=`${c.adminNav('drafts')}${sectionHeader(L('Чернетки на цьому пристрої','Szkice na tym urządzeniu'),L('Текст і вибрані фото зберігаються у цьому браузері окремо для твого облікового запису. Очищення даних браузера видалить їх.','Tekst i zdjęcia są zapisane w tej przeglądarce osobno dla Twojego konta. Wyczyszczenie danych przeglądarki je usunie.'))}<div id="hp-draft-list">${c.t('loading')}</div>`;
 try{const rows=await drafts.listDrafts(user);if(c.view!=='drafts'||c.db.currentUserId!==user)return;q('#hp-draft-list').innerHTML=rows.map(d=>`<article class="hp-draft-row"><div><strong>${E(d.values.name||L('Новий товар','Nowy produkt'))}</strong><small>${new Date(d.savedAt).toLocaleString(c.lang==='pl'?'pl-PL':'uk-UA')}</small></div>${button('open-draft',L('Продовжити','Kontynuuj'),false,`data-id="${d.id||''}"`)}${button('delete-draft',c.t('delete'),false,`data-id="${d.id||''}"`)}</article>`).join('')||`<p>${L('Немає незавершених чернеток.','Brak niedokończonych szkiców.')}</p>`;}catch{if(q('#hp-draft-list'))q('#hp-draft-list').textContent=L('Браузер не дозволив доступ до чернеток.','Przeglądarka nie pozwoliła na dostęp do szkiców.');}}
 async function loadVersions(id){versionProduct=c.products.find(p=>p.id===id);versions=[];versionError=false;versionLoading=true;navigate('versions');try{versions=await c.db.listVersions(id);}catch{versionError=true;}finally{versionLoading=false;if(c.view==='versions')c.render();}}
 function renderVersions(){content().innerHTML=`${c.adminNav('versions')}${sectionHeader(L('Історія версій','Historia wersji'),E(versionProduct?.name||''))}${versionLoading?c.t('loading'):versionError?`<p role="alert">${c.t('error')}</p>${button('versions',L('Повторити','Ponów'),false,`data-id="${versionProduct?.id}"`)}`:`<p>${L('Останні 50 збережень. Відновлення повертає назву, ціну, статус, фото й характеристики та створює новий запис в історії.','Ostatnie 50 zapisów. Przywrócenie odtwarza nazwę, cenę, status, zdjęcia i parametry oraz tworzy nowy wpis w historii.')}</p>${versions.map((v,i)=>{const p=fromRow(v.snapshot);return `<article class="hp-version-row"><div><strong>${new Date(v.saved_at).toLocaleString(c.lang==='pl'?'pl-PL':'uk-UA')}</strong><p>${E(p.name)} · ${effectivePrice(p)} zł · ${c.t('statuses')[p.status]}</p><details><summary>${L('Переглянути дані','Zobacz dane')}</summary><div class="hp-version-data"><p>${E(p.condition)} · ${E(p.warranty)}</p><p>${E([p.cpu,p.ram&&p.ram+' GB RAM',p.ssd&&p.ssd+' GB',p.gpu,p.screen].filter(Boolean).join(' · '))}</p><p>${E(p.descUk)}</p><p>${E(p.descPl)}</p><div class="hp-version-images">${(p.images||[]).map(path=>`<img src="${E(c.db.photoUrl(path))}" alt="${E(p.name)}" loading="lazy">`).join('')}</div></div></details></div>${i===0?`<span>${L('Поточна','Aktualna')}</span>`:button('restore-version',L('Відновити цю версію','Przywróć tę wersję'),false,`data-id="${v.id}"`)}</article>`;}).join('')}`}`;}
 function readForm(){const form=q('#hp-form');if(!form)return null;return {...draftValues(new FormData(form)),id:c.editId,updated_at:editorBase};}
 function draftStatus(text,error=false){const el=q('#hp-draft-status');if(el){el.textContent=text;el.classList.toggle('hp-draft-error',error);}}
 function captureDraft(){clearTimeout(draftTimer);const values=readForm();if(!c.admin||!values||!dirty||draftPending)return draftChain;const user=c.db.currentUserId,id=c.editId,generation=editGeneration;
 const images=c.images.map(p=>typeof p==='string'?p:{blob:p.blob});draftStatus(L('Зберігаємо чернетку…','Zapisywanie szkicu…'));
 const job=()=>drafts.saveDraft(user,id,{values,images,baseUpdatedAt:editorBase}).then(()=>{if(generation===editGeneration){draftError=false;draftStatus(L('Чернетку збережено на цьому пристрої','Szkic zapisany na tym urządzeniu'));}}).catch(()=>{if(generation===editGeneration){draftError=true;draftStatus(L('Чернетку не збережено: перевір вільне місце та дозвіл браузера.','Nie zapisano szkicu: sprawdź miejsce i uprawnienia przeglądarki.'),true);}});
 draftChain=draftChain.then(job,job);return draftChain;
 }
 function changed(){if(restoring||!q('#hp-form'))return;dirty=true;if(draftPending){draftStatus(L('Спочатку віднови або відкинь попередню чернетку.','Najpierw przywróć lub odrzuć poprzedni szkic.'),true);return;}draftStatus(L('Є незбережені зміни…','Są niezapisane zmiany…'));clearTimeout(draftTimer);draftTimer=setTimeout(captureDraft,450);}
 function fillForm(values){restoring=true;c.formCategory(Number(values.cat||0),values);const form=q('#hp-form');for(const el of form.elements){if(!el.name||el.type==='file')continue;if(el.type==='checkbox')el.checked=csv(values[el.name]).includes(el.value);else if(values[el.name]!==undefined)el.value=String(values[el.name]);}restoring=false;}
 async function formReady(p){const form=q('#hp-form');if(!form||form===editorForm)return;editorForm=form;editorBase=p.updated_at||null;draftPending=null;dirty=false;draftError=false;const generation=++editGeneration;
 form.insertAdjacentHTML('afterbegin',`<div class="hp-draft-tools"><span id="hp-draft-status" role="status">${L('Чернетка зберігається автоматично на цьому пристрої','Szkic zapisuje się automatycznie na tym urządzeniu')}</span>${button('preview',L('Переглянути перед публікацією','Podgląd przed publikacją'))}${p.id?button('versions',L('Історія версій','Historia wersji'),false,`data-id="${p.id}"`):''}</div><div id="hp-draft-restore"></div>`);
 const media=form.querySelector('input[name="telegramPost"]')?.closest('.hp-field');media?.insertAdjacentHTML('afterend',`<label class="hp-field hp-wide">${L('Які фото показано','Jakie zdjęcia pokazujesz')}<select name="photoKind">${Object.entries(photoLabels()).map(([v,l])=>`<option value="${v}" ${p.photoKind===v?'selected':''}>${l}</option>`).join('')}</select></label>`);
 try{const saved=await drafts.readDraft(c.db.currentUserId,p.id);if(generation!==editGeneration||q('#hp-form')!==form)return;if(saved){draftPending=saved;q('#hp-draft-restore').innerHTML=`<div class="hp-draft-banner"><strong>${L('Є незавершена чернетка','Jest niedokończony szkic')}</strong><span>${new Date(saved.savedAt).toLocaleString(c.lang==='pl'?'pl-PL':'uk-UA')}</span>${saved.baseUpdatedAt!==editorBase&&p.id?`<p>${L('Опублікований товар змінився після створення чернетки. Перед збереженням перевір актуальні дані.','Opublikowany produkt zmienił się po utworzeniu szkicu. Sprawdź aktualne dane przed zapisaniem.')}</p>`:''}${button('resume-draft',L('Відновити чернетку','Przywróć szkic'),true)}${button('discard-draft',L('Відкинути чернетку','Odrzuć szkic'))}</div>`;}}catch{draftError=true;draftStatus(L('Автозбереження недоступне у цьому браузері.','Autozapis niedostępny w tej przeglądarce.'),true);}
 }
 async function afterSave(){clearTimeout(draftTimer);await draftChain;await drafts.removeDraft(c.db.currentUserId,c.editId).catch(()=>{});dirty=false;draftPending=null;editorForm=null;editGeneration++;}
 function beforeLeave(){return captureDraft();}
 function preview(){const p=readForm();if(!p)return;const issues=productIssues({...p,images:c.images});const dialog=document.createElement('dialog');dialog.className='hp-preview-dialog';dialog.innerHTML=`<div class="hp-preview-head"><h2>${L('Попередній перегляд','Podgląd')}</h2>${button('close-preview',L('Закрити','Zamknij'))}</div><p class="hp-muted">${L('Товар ще не опубліковано.','Produkt nie został jeszcze opublikowany.')}</p><div class="hp-preview-layout"><div class="hp-preview-images">${c.images.map(p=>`<img src="${E(typeof p==='string'?c.db.photoUrl(p):p.url)}" alt="${L('Фото товару','Zdjęcie produktu')}">`).join('')}</div><div><h2>${E(p.name||L('Назва товару','Nazwa produktu'))}</h2><strong class="hp-money">${effectivePrice({...p,price:Number(p.price)||0})} zł</strong><p>${E(p.cpu)} · ${E(p.ram)} GB RAM · ${E(p.ssd)} GB</p><p>${E(p.condition)} · ${E(p.warranty)}</p><p>${photoLabels()[p.photoKind||'']}</p><p class="hp-description">${E(c.lang==='pl'?p.descPl:p.descUk)}</p></div></div>${issues.length?`<p class="hp-note">${issues.map(k=>issueLabels()[k]).join(' · ')}</p>`:''}`;c.root.append(dialog);dialog.addEventListener('close',()=>dialog.remove());dialog.showModal();}
 function renderTelegramBanner(){
  let banner=q('#hm-telegram-banner');
  if(!banner){banner=document.createElement('aside');banner.id='hm-telegram-banner';banner.className='hm-top-banner';q('#hp-categories')?.after(banner);}
  const publicView=['home','catalog','detail','start','finder','shared','compare','cart'].includes(c.view);
  banner.hidden=!publicView;
  if(!publicView){banner.innerHTML='';return;}
  const slot=c.view==='start'?'start':c.view==='detail'?'product':'catalog';
  banner.setAttribute('aria-label',L('Переваги Telegram-каналу','Korzyści kanału Telegram'));
  banner.innerHTML=`<a href="${E(channelUrl(slot))}" target="_blank" rel="noopener noreferrer" data-track-target="telegram_channel" data-track-placement="${slot}"><svg class="hm-banner-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="m22 2-7 20-4-9-9-4Z"/><path d="M22 2 11 13"/></svg><span class="hm-banner-copy"><strong>${L('Унікальні пропозиції та безкоштовна доставка','Wyjątkowe oferty i bezpłatna dostawa')}</strong><span>${L('Для підписників нашого Telegram-каналу','Dla subskrybentów naszego kanału Telegram')}</span></span><span class="hm-banner-cta">${L('Підписатися','Dołącz do kanału')} <span aria-hidden="true">↗</span></span></a>`;
 }
 function afterRender(){
 const view=c.view;
 renderTelegramBanner();
 if(['quality','settings','drafts','versions'].includes(view)&&!c.admin)return;
 if(view==='quality')renderQuality();if(view==='settings')renderSettings();if(view==='drafts')renderDraftList();if(view==='versions')renderVersions();
 if(view==='finder')renderFinder();if(view==='shared')renderShared();
 if(c.admin&&['admin','picks','quality','settings','drafts','versions','reviews','stats','activity'].includes(view)){q('.hp-admin-tabs')?.insertAdjacentHTML('afterend',adminTabs());}
 if(view==='admin'){const count=c.products.filter(p=>[0,3].includes(p.status)&&productIssues(p).length).length;q('.hp-intro')?.insertAdjacentHTML('afterend',`<aside class="hp-admin-health"><span>${L('Картки, які варто доповнити','Karty do uzupełnienia')}: <b>${count}</b></span>${button('quality',L('Перевірити','Sprawdź'))}${button('drafts',L('Мої чернетки','Moje szkice'))}</aside>`);}
 if(view==='reviews'){const complete=c.reviews.filter(r=>r.is_published&&r.image_path&&r.purchased_model&&r.customer_name).length;q('.hp-intro')?.insertAdjacentHTML('afterend',`<aside class="hp-admin-health"><div><strong>${L('Повні відгуки зі скрином і моделлю','Pełne opinie ze zrzutem i modelem')}: ${complete}</strong><p>${L('Рекомендовано 4–6 реальних відгуків. Додай ім’я, придбану модель і текст клієнта. Перед публікацією приховай особисті контакти на скриншоті.','Warto dodać 4–6 prawdziwych opinii: imię, kupiony model i tekst klienta. Przed publikacją ukryj prywatne dane na zrzucie.')}</p></div></aside>`);}
 if(view==='stats'&&!c.statsLoading&&!c.statsError)content().insertAdjacentHTML('beforeend',renderPlacements()+insights.render());
 if(view==='home')q('#hm-home-terms')?.insertAdjacentHTML('beforeend',trustBlock());

 if(view==='detail'){const p=c.products.find(p=>p.id===c.selected);if(p){remember(p.id);q('.hp-gallery-panel')?.insertAdjacentHTML('beforeend',`<p class="hp-photo-origin">${p.photoKind ? photoLabels()[p.photoKind] : L('Фото для ознайомлення з товаром. Стан і комплектацію уточнюй перед замовленням.','Zdjęcia poglądowe. Potwierdź stan i wyposażenie przed zamówieniem.')}${p.photoKind!=='actual'&&p.telegramPost?`<br>${L('Переглянь живий огляд за посиланням у Telegram.','Zobacz prezentację pod linkiem w Telegramie.')}`:''}</p>`);q('.hp-detail-lower')?.insertAdjacentHTML('afterend',trustBlock());q('.hp-buy-panel')?.insertAdjacentHTML('beforeend',`<div class="hp-product-subscribe"><span>${L('Підписникам каналу — безкоштовна доставка та спеціальні пропозиції.','Subskrybenci kanału otrzymują bezpłatną dostawę i oferty specjalne.')}</span><a href="${E(channelUrl('product'))}" data-track-target="telegram_channel" data-track-placement="product" target="_blank" rel="noopener noreferrer">${c.t('subscribe')} ↗</a></div>`);}}
 if(['home','catalog','detail'].includes(view))content().insertAdjacentHTML('beforeend',recentBlock());
 if(view==='cart'&&c.cart.length){q('.hp-summary')?.insertAdjacentHTML('beforeend',`<div class="hp-share-selection">${button('share-selection',L('Поділитися моїм вибором','Udostępnij moją listę'))}<p>${L('Посилання містить лише список товарів.','Link zawiera wyłącznie listę produktów.')}</p></div>`);}
 for(const el of c.root.querySelectorAll('a[data-track-target="telegram_channel"]')){const slot=el.dataset.trackPlacement||(el.closest('.hp-bottom')?'footer':el.classList.contains('hp-mobile-telegram')?'floating':view==='start'?'start':'catalog');el.dataset.trackPlacement=slot;el.href=channelUrl(slot);}
 for(const el of c.root.querySelectorAll('.hp-trust-grid > div')){const i=[...el.parentElement.children].indexOf(el);const value=settings.trust?.[TRUST_SECTIONS[i]]?.[c.lang];if(value)el.querySelector('p').textContent=value;}
 if(['home','catalog'].includes(view)){for(const label of c.root.querySelectorAll('.hp-hero-proof span,.hp-stock-benefit small'))if(label.textContent.trim()===c.t('realPhotos'))label.textContent=L('Живі огляди в Telegram','Prezentacje w Telegramie');}
 }
 async function handleClick(b){
 const action=b.dataset.grow;if(!action)return false;
 if(action==="check-photos"){if(c.admin)await checkPhotos();return true;}
 if(['quality','settings','drafts','versions','open-draft','delete-draft','restore-version','resume-draft','discard-draft','preview','reload-settings'].includes(action)&&!c.admin)return true;
 if(['quality','settings','drafts','finder'].includes(action)){await beforeLeave();navigate(action);}
 else if(action==='catalog'){c.setView('catalog');history.replaceState(null,'','/');c.render();window.scrollTo(0,0);}
 else if(action==='budget'){q('#hp-quiz-form input[name="budget"]').value=b.dataset.value;}
 else if(action==='quiz-back'){Object.assign(quiz,Object.fromEntries(new FormData(q('#hp-quiz-form'))));quizStep=Math.max(0,quizStep-1);c.render();}
 else if(action==='quiz-reset'){quizStep=0;quizResults=false;c.render();}
 else if(action==='clear-recent'){recent=[];c.writeLocal('hmg-recent-products',recent);c.render();}
 else if(action==='share-selection'){const url=shareSelection(c.cart,location.origin);try{await navigator.clipboard.writeText(url);c.notify(L('Посилання на вибір скопійовано.','Link do listy skopiowany.'));}catch{const box=document.createElement('input');box.readOnly=true;box.value=url;box.className='hp-share-fallback';b.after(box);box.select();}}
 else if(action==='shared-add'){c.addSelection(shared.filter(id=>c.products.some(p=>p.id===id&&availableProduct(p))));c.notify(L('Додано до твого вибору.','Dodano do Twojej listy.'));}
 else if(action==='versions'){await beforeLeave();await loadVersions(Number(b.dataset.id));}
 else if(action==='restore-version'){const v=versions.find(v=>v.id===Number(b.dataset.id));if(!v||!confirm(L('Відновити цю версію? Поточні ціна, статус, фото й характеристики будуть замінені.','Przywrócić tę wersję? Obecna cena, status, zdjęcia i parametry zostaną zastąpione.')))return true;await c.run(async()=>{await c.db.restoreVersion(v.id,versionProduct.updated_at);await c.refresh();await loadVersions(v.product_id);c.notify(L('Версію відновлено. Зміна записана в журналі.','Wersja przywrócona. Zmiana zapisana w dzienniku.'));});}
 else if(action==='preview'){await captureDraft();preview();}
 else if(action==='close-preview'){b.closest('dialog')?.close();}
 else if(action==='resume-draft'){if(draftPending){const d=draftPending;draftPending=null;c.setImages(d.images.map(x=>typeof x==='string'?x:{blob:x.blob,url:URL.createObjectURL(x.blob)}));fillForm(d.values);dirty=true;q('#hp-draft-restore').innerHTML='';c.showUploads();await captureDraft();}}
 else if(action==='discard-draft'){await drafts.removeDraft(c.db.currentUserId,c.editId);draftPending=null;q('#hp-draft-restore').innerHTML='';draftStatus(L('Починай редагування — зміни збережуться автоматично.','Zacznij edycję — zmiany zapiszą się automatycznie.'));if(dirty)await captureDraft();}
 else if(action==='open-draft'){await c.openEditor(Number(b.dataset.id)||null);}
 else if(action==='delete-draft'){if(confirm(L('Видалити цю локальну чернетку?','Usunąć ten lokalny szkic?'))){await drafts.removeDraft(c.db.currentUserId,Number(b.dataset.id)||null);await renderDraftList();}}
 else if(action==='reload-settings'){await reloadSettings();c.render();}
 return true;
 }
 async function handleSubmit(form){if(form.id==='hp-form'&&draftPending){c.notify(L('Спочатку віднови або відкинь попередню чернетку.','Najpierw przywróć lub odrzuć poprzedni szkic.'));return true;}if(form.id==='hp-quiz-form'){Object.assign(quiz,Object.fromEntries(new FormData(form)));if(quizStep<2)quizStep++;else quizResults=true;c.render();window.scrollTo(0,0);return true;}
 if(form.id==='hp-settings-form'){if(!c.admin)return true;const d=Object.fromEntries(new FormData(form));await c.run(async()=>{try{const value=validateSettings({links:Object.fromEntries(LINK_SLOTS.map(k=>[k,d['link_'+k]])),trust:Object.fromEntries(TRUST_SECTIONS.map(k=>[k,Object.fromEntries(['uk','pl'].map(l=>[l,d['trust_'+k+'_'+l]]))]))});await c.db.saveSettings({...value,updated_at:settings.updated_at});await reloadSettings();if(settingsError)throw Error('saveUnconfirmed');c.render();q('#hp-settings-message').textContent=L('Збережено. Зміни вже використовуються на сайті.','Zapisano. Zmiany są już używane na stronie.');}catch(err){q('#hp-settings-message').textContent=message(err);}});return true;}return false;}
 c.root.addEventListener('input',e=>{if(e.target.closest('#hp-form'))changed();});
 c.root.addEventListener('change',e=>{if(e.target.closest('#hp-form')&&e.target.type!=='file')changed();});
 return {afterRender,handleClick,handleSubmit,reloadSettings,formReady,changed,captureDraft,beforeLeave,afterSave,message,get editorBase(){return editorBase;},get dirty(){return dirty;},get draftPending(){return !!draftPending;}};
}
