import {journey,missedSearches} from './insights-core.js';
export function createInsights(c){
 const E=c.esc,L=(u,p)=>c.lang==='pl'?p:u;
 let source='',device='',product='';
 function render(){
 const all=c.analyticsEvents,events=all.filter(e=>(!source||e.traffic_source===source)&&(!device||e.device_type===device));
 const j=journey(events,product), searches=missedSearches(events);
 const options=(values,current)=>`<option value="">${L('Усі','Wszystkie')}</option>`+values.map(([v,l])=>`<option value="${E(v)}" ${String(v)===current?'selected':''}>${E(l)}</option>`).join('');
 const stages=[[L('Відвідали сайт','Odwiedzili stronę'),j.visits],[L('Відкрили товар','Obejrzeli produkt'),j.views],[L('Потім додали до вибору','Następnie dodali do listy'),j.cart],[L('Потім натиснули «Замовити»','Następnie kliknęli „Zamów”'),j.orders]];
 return `<section id="hm-insights" class="hp-stat-panel hp-placements"><h2>${L('Шлях до звернення','Droga do kontaktu')}</h2><p>${L('Сесії за вибраний вище період. Наступні кроки враховуються в часовому порядку в межах однієї сесії. Це кліки, не оплачені замовлення. Дані лише за згодою на аналітику; початок сесії може бути поза періодом.','Sesje z okresu wybranego powyżej. Kolejne kroki liczymy chronologicznie w tej samej sesji. To kliknięcia, nie opłacone zamówienia. Dane tylko za zgodą; początek sesji może przypadać poza okresem.')}</p><div class="hp-form-grid">${[['source',L('Джерело','Źródło'),options([...new Set(all.map(e=>e.traffic_source||'direct'))].map(v=>[v,v]),source)],['device',L('Пристрій','Urządzenie'),options([['mobile',L('Телефон','Telefon')],['tablet',L('Планшет','Tablet')],['desktop',L('Комп’ютер','Komputer')]],device)],['product',L('Товар для шляху','Produkt dla ścieżki'),options(c.products.map(p=>[p.id,p.name]),product)]].map(([k,l,o])=>`<label class="hp-field">${l}<select data-insight="${k}">${o}</select></label>`).join('')}</div><div class="hp-quality-list">${stages.map(([l,n])=>`<article><strong>${l}</strong><span>${n}</span><progress aria-label="${l}" max="${Math.max(j.visits,j.views,1)}" value="${n}"></progress></article>`).join('')}</div><p><strong>${L('Звернення після перегляду, з вибором або без нього','Kontakt po obejrzeniu, z listą lub bez')}: ${j.direct} · ${j.views?Math.round(j.direct/j.views*100):0}%</strong></p><p>${L('Сесії з переходом у канал','Sesje z przejściem do kanału')}: ${j.channel}. ${L('Перехід не підтверджує підписку. Замовлення всього кошика без ID товару не приписуються окремій моделі.','Przejście nie potwierdza subskrypcji. Kontakt dotyczący całego koszyka bez ID produktu nie jest przypisywany do modelu.')}</p><h2>${L('Що шукали й не знайшли','Czego szukali bez wyników')}</h2><p>${L('За цими самими джерелом і пристроєм, незалежно від вибраного товару. Запис після паузи 1,2 с; контакти та посилання не записуємо. Збір починається після цього оновлення. Нуль результатів із фільтрами не означає відсутність товару в усьому каталозі.','Dla tego samego źródła i urządzenia, niezależnie od produktu. Zapis po pauzie 1,2 s; kontaktów i linków nie zapisujemy. Zbieranie od tej aktualizacji. Brak wyników z filtrami nie oznacza braku produktu w całym katalogu.')}</p><div class="hp-table-scroll"><table><thead><tr><th>${L('Запит','Zapytanie')}</th><th>${L('Умови','Warunki')}</th><th>${L('Пошуки','Wyszukiwania')}</th><th>${L('Відвідувачі','Odwiedzający')}</th></tr></thead><tbody>${searches.map(r=>`<tr><td>${E(r.term)}</td><td>${r.filtered?L('Із фільтрами/категорією','Z filtrami/kategorią'):L('Весь каталог','Cały katalog')}</td><td>${r.count}</td><td>${r.visitors.size}</td></tr>`).join('')||`<tr><td colspan="4">${L('За цей період немає записів.','Brak zapisów w tym okresie.')}</td></tr>`}</tbody></table></div></section>`;
 }
 c.root.addEventListener('change',e=>{const key=e.target.dataset.insight;if(!key||!c.admin)return;if(key==='source')source=e.target.value;if(key==='device')device=e.target.value;if(key==='product')product=e.target.value;c.root.querySelector('#hm-insights').outerHTML=render();});
 return {render};
}
